# DESC: Expose actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: *

  # DESC: Enable the actuator endpoint: "info"
  info:
    env:
      enabled: true

  # DESC: Enable gateway related actuator endpoints
  endpoint:
    gateway:
      enabled: true
