# DESC: Actuator endpoint management
management:
  endpoints:
    # DESC: Expose actuator endpoints
    web:
      exposure:
        include: '*'

  # DESC: Enable the "/actuator/info" endpoint
  info:
    env:
      enabled: true

  # DESC: Enable the "actuator/gateway" endpoint
  endpoint:
    gateway:
      enabled: true
